image: Visual Studio 2015
platform: x86
configuration: Release

environment:
  matrix:
    - PYTHON: "C:\\Python36"

install:
  - "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\devenv.exe"
  - mkdir blender-build
  - cd blender-build
  - mkdir build
  - git clone git://git.blender.org/blender.git
  - cd blender
  - git submodule update --init --recursive
  - git submodule foreach git checkout master
  - git submodule foreach git pull --rebase origin master
  - cd ..
  - svn checkout --quiet https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14  lib/windows_vc14
  - cd build
  - cmake -DWITH_PLAYER=OFF -DWITH_PYTHON_MODULE=ON -DWITH_PYTHON_INSTALL=OFF -DPYTHON_VERSION=3.6 ../blender
  - "C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/devenv.exe" Blender.sln /Build Release /Project INSTALL
