image: Visual Studio 2015
platform: x86
configuration: Release

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - PYTHON: "C:\\Python36"

install:
  - set PATH=%VS140COMNTOOLS%..\IDE;%PATH%
  - IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\blender-build mkdir blender-build
  - cd blender-build
  - mkdir build
  - git clone git://git.blender.org/blender.git
  - cd blender
  - git submodule update --init --recursive
  - git submodule foreach git checkout master
  - git submodule foreach git pull --rebase origin master
  - cd ..
  - IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\blender-build\lib svn checkout --quiet https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14  lib/windows_vc14
  - cd build
  - cmake -DWITH_PLAYER=OFF -DWITH_PYTHON_MODULE=ON -DWITH_PYTHON_INSTALL=OFF -DPYTHON_VERSION=3.6 ../blender
  - devenv.exe Blender.sln /Build Release /Project INSTALL

cache:
  - blender-build\lib
